### ISSUE TITLE
Make the Messages in the DatagramLayer independent of the address

### ISSUE THREAD

**Issue by bjoerntm** [christoph-lucas/bifrost#14]
The messages communicated via send() and receive() in the DatagramLayer should only contain payload information. The (receiver's) address should be set while instantiating the channel object.

Several "sending" channels will share the same actual UDP socket, and they will actually also share it with the receiving channel.

**Comment by bjoerntm** [comment]
This is actually based on research discussions with Ueli. The rough idea is: in communication such as (insecure) UDP communication, one should view the channels as "one-way multi-sender single-receiver" channels. (Indeed, one could have left out the sender's address from the bare packet format, and have the client specify it in the higher-level protocol if it expects a reply.) The fact that we use the same UDP Port for practical reasons is fine, but we may want to express that differently.

**Comment by christoph-lucas** [comment]
Ehrlich gesagt klingt das für mich nach einer nicht so tollen Idee. Das würde bedeuten, dass wir bereits auf Datagram-Ebene ein Multiplexing haben. Sprich, das ganze Session-Zeugs würde in die falsche Schicht geschoben, oder (noch schlimmer) verdoppelt. Den "Gegenstellen-spezifische-Endpunkt" (wie er hier designed ist) bekommen wir nach dem Session-Multiplexing (genau dafür ist es da). Nachrichten für so einen Multiplexed-Endpoint enthalten dann wirklich nur noch den Payload, während der Multiplexed-Endpoint selber im Konstruktor die Informationen für die Gegenstelle enthält.

Der zweite Teil klingt für mich, als gäbe es verschiedene Objekte für Empfangen und Senden. Auch das klingt für mich nach einer unnötigen Verkomplizierung.

**Comment by bjoerntm** [comment]
So ganz verstehe ich Deine Antwort nicht. "Wirklich" Multiplexing würde da gar nicht passieren, zumindest nicht insofern dass die Nachrichten sich ändern würden. Möglicherweise diskutieren wir das am besten mal mit Zettel und Stift, ist auch momentan kein dringender Punkt. Es gibt aber durchaus gute Gründe dafür:
- die Nachrichten können in allen Schichten einfach Blobs sein und tragen keine semantische Information für die unteren Schichten,
- es hält das Protokoll unabhängiger davon wie die Nachrichten geschickt werden, etwa per UDP in die eine Richtung und per Brieftaube zurück. Nein, klar, die Idee ist eher in die Richtung wechselnde IP Adressen bei mobilen Clients zu unterstützen.
- Es ist das, was einem unsichere Datagram Kommunikation eigentlich gibt. Aber dazu: Zettel und Stift.

Lass uns den Issue einfach mal schlafen lassen bis wir "live" darüber diskutieren können.

**Comment by christoph-lucas** [comment]
Partially replaced #19
