### ISSUE TITLE
Double checking of MultiplexingID

### ISSUE THREAD

**Issue by bjoerntm** [christoph-lucas/bifrost#49]
The receive methods in ch.bifrost.core.impl.datagram.MultiplexedDatagramEndpoint check the MultiplexingID although ch.bifrost.server.impl.datagram.DatagramEndpointMultiplexer does guarantee that only packets with the correct ID are in there. We may want to convert the check into an assertion since it actually cannot happen.

This may actually point to a different idea: Maybe the DatagramEndpointMultiplexer should actually handle the conversion of the message (removing the MultiplexingID) and the MultiplexedDatagramEndpoint may become independent of the actual multiplexing and be a generic tool to get datagrams from the queue?

**Comment by christoph-lucas** [comment]
Der doppelte Check war nur im Server. Der Check im MultiplexedDatagramEndpoint war im Client der einzige ;). Hab ihn jetzt in den ClientMultiplexedDatagramEndpoint geschoben...
